name: gradle-ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: 'jdk'
    - name: Make gradle executable
      run: chmod +x shadowJar
    - name: Build artifacts
      run: ./gradlew build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: smpcore-bukkit/build/libs
